remote_theme:  mmistakes/jekyll-theme-basically-basic
lang: en-US
title: K(not) A Conversation
email: ambika@ajaibghar.com
description: "Knot a Conversation project"
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/icons/logo.svg

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown

plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _recipes
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      read_time: true
